version: "3.7"
services:
  app:
    image: indicadoreslist:latest
    container_name: indicadoreslist
    restart: unless-stopped
    ports:
      - 8000:8000
    networks:
      network1:
        ipv4_address: 10.5.0.5
  nginx:
    image: indicadoresfront:latest
    container_name: indicadoresfront
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./:/var/www
    networks:
      network1:
        ipv4_address: 10.5.0.6
  reverseproxy:
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx2.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      network1:
        ipv4_address: 10.5.0.7
networks:
  network1:
    name: sercop
    external: true

