version: "3.7"
services:
  app:
    image: indicadoreslist:latest
    container_name: indicadoreslist
    restart: unless-stopped
    ports:
      - 443:8000
    networks:
      network:
        ipv4_address: 10.5.0.5
  nginx:
    image: indicadoresfront:latest
    container_name: indicadoresfront
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
    networks:
      network:
        ipv4_address: 10.5.0.6

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1
